=== felipesalinas9412/qamet-frmktest-playwright-javascript-lib-qa/schemas/eligibility/group-registration/putGroupRegistrationSchema.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GroupRegistrationBasicEjemplohastatenerelReal",
  "type": "object",
  "additionalProperties": true,
  "properties": {
    "GroupRegistrationId": { "type": "integer" },
    "GroupNumber": { "type": "string" },
    "Description": { "type": "string" },

    "RegistrationDateFrom": { "type": "string", "pattern": "^\\d{4}-\\d{2}-\\d{2}$" },
    "RegistrationDateTo":   { "type": "string", "pattern": "^\\d{4}-\\d{2}-\\d{2}$" },
    "PolicyEffectiveDate":  { "type": "string", "pattern": "^\\d{4}-\\d{2}-\\d{2}$" },

    "EmployerContribution":   { "type": ["number", "null"] },
    "GroupEmailContact":      { "type": "string" },
    "ProducerNumber":         { "type": "string" },
    "EmployerContributionFlag": { "type": ["boolean", "null"] },

    "EmloadPlanNumber":  { "type": "string" },
    "EmloadClass":       { "type": "string" },
    "EmloadPCS":         { "type": "string" },
    "EmloadSpoBenClass": { "type": "string" },
    "EmloadDepBenClass": { "type": "string" },

    "GroupType": { "type": "string" },

    "PlansByLocationFlag": { "type": ["boolean", "null"] },
    "EmloadPerLocationFlag": { "type": ["boolean", "null"] },
    "LifeFlag": { "type": ["boolean", "null"] },
    "LifeOptionalFlag": { "type": ["boolean", "null"] },
    "JointFlag": { "type": ["boolean", "null"] },
    "ColateralFlag": { "type": ["boolean", "null"] },

    "Active": { "type": ["boolean", "null"] },

    "CreatedBy":   { "type": "string" },
    "CreatedDate": { "type": "string", "pattern": "^\\d{4}-\\d{2}-\\d{2}$" }
  },
  "required": [
    "GroupRegistrationId",
    "GroupNumber",
    "Description",
    "RegistrationDateFrom",
    "RegistrationDateTo",
    "PolicyEffectiveDate",
    "CreatedBy",
    "CreatedDate"
  ]
}

=== felipesalinas9412/qamet-frmktest-playwright-javascript-lib-qa/data/eligibility/group-registration/put-GroupRegistrationById.json
{
  "GroupRegistrationId": 6,
  "GroupNumber": "357185",
  "Description": "Empleadossstemp",
  "RegistrationDateFrom": "2025-08-01",
  "RegistrationDateTo": "2025-08-31",
  "PolicyEffectiveDate": "2004-06-01",
  "EmployerContribution": 125,
  "GroupEmailContact": "jcolonc@mapfrepr.com;fpereira@mapfrepr.com",
  "ProducerNumber": "(787)-888-8888",
  "EmployerContributionFlag": true,
  "EmloadPlanNumber": "MFC - 71",
  "EmloadClass": "2A",
  "EmloadPCS": "W603 Q096",
  "EmloadSpoBenClass": "A",
  "EmloadDepBenClass": "A",
  "GroupType": "C",
  "PlansByLocationFlag": true,
  "EmloadPerLocationFlag": false,
  "LifeFlag": false,
  "LifeOptionalFlag": null,
  "JointFlag": true,
  "ColateralFlag": true,
  "Active": true,
  "CreatedBy": "EMUNIZ",
  "CreatedDate": "2025-08-05"
}
